### ISSUE TITLE
start multiple wptagents in a single PC

### ISSUE THREAD

**Issue by chrischjh** [WPO-Foundation/wptagent#222]
I'm trying to start up multiple wptagents in a single Windows PC, the purpose is to achieve more concurrency for a sinlge Location. But I got the port 8888 conflict when starting up the second one, can I customize the extension server port? Or is there another way to achieve the same? thanks a lot
```
17:10:31.107 - Starting extension server on port 8888
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "d:\wptagent\internal\message_server.py", line 168, in run
    application.listen(8888, '127.0.0.1')
  File "C:\Python27\lib\site-packages\tornado\web.py", line 2042, in listen
    server.listen(port, address)
  File "C:\Python27\lib\site-packages\tornado\tcpserver.py", line 143, in listen
    sockets = bind_sockets(port, address=address)
  File "C:\Python27\lib\site-packages\tornado\netutil.py", line 168, in bind_sockets
    sock.bind(sockaddr)
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted
```

**Comment by pmeenan** [comment]
You can't. You can run them in VMs if you want to increase system utilization but only one instance can run at a time on a given os. There are a lot more Singleton conflicts than just the port:

- traffic shaping is global to the machine and shared
- video capture requires the browser being recorded be placed in a specific position
- browser cache/cookies


________________________________
