### ISSUE TITLE
Firefox seems to be broken

### ISSUE THREAD

**Issue by nilskuhn** [WPO-Foundation/wptagent#278]
Hi there,

I am not able to run tests with Firefox since yesterday :( 
That's true for our private instances running the latest agent. On official instance I am observing same error `Unhandled exception running test: cannot import name ChromiumProfile`: 

https://www.webpagetest.org/result/190808_K9_2ee8bcf9a98faf6f3aced5a24596c8f5/ 

The stacktrace looks like it could be related to the [deprecation of marionette lib](https://lists.mozilla.org/pipermail/tools-marionette/2019-January/000068.html) and [this issue](https://github.com/WPO-Foundation/wptagent/issues/233):
```
08:32:33.681 - Unhandled exception running test: cannot import name errors
Traceback (most recent call last):
  File "C:\WptTestAgent\wptagent\wptagent.py", line 110, in run_testing
    self.run_single_test()
  File "C:\WptTestAgent\wptagent\wptagent.py", line 168, in run_single_test
    browser.launch(self.job, self.task)
  File "C:\WptTestAgent\wptagent\internal\firefox.py", line 122, in launch
    from marionette_driver.marionette import Marionette
  File "C:\Python27\lib\site-packages\marionette_driver\__init__.py", line 9, in <module>
    from marionette_driver import (
  File "C:\Python27\lib\site-packages\marionette_driver\expected.py", line 9, in <module>
    from . import errors
ImportError: cannot import name errors
Traceback (most recent call last):
  File "C:\WptTestAgent\wptagent\wptagent.py", line 110, in run_testing
    self.run_single_test()
  File "C:\WptTestAgent\wptagent\wptagent.py", line 168, in run_single_test
    browser.launch(self.job, self.task)
  File "C:\WptTestAgent\wptagent\internal\firefox.py", line 122, in launch
    from marionette_driver.marionette import Marionette
  File "C:\Python27\lib\site-packages\marionette_driver\__init__.py", line 9, in <module>
    from marionette_driver import (
  File "C:\Python27\lib\site-packages\marionette_driver\expected.py", line 9, in <module>
    from . import errors
ImportError: cannot import name errors
```

**Comment by zeman** [comment]
@pmeenan can confirm we're seeing this issue as well.

**Comment by pmeenan** [comment]
I'm traveling today and tomorrow so I'm not sure if I'll make progress on
it over the weekend. Ripping out marionette and replacing it with webdriver
will either go really easily or be a complete nightmare depending on what
capabilities are exposed though webdriver. I'm assuming the prefs will be
available. Just not sure about the support for installing extensions.

**Comment by pmeenan** [comment]
Doesn't look like it is the deprecation. Looks like they updated the [mozrunner](https://pypi.org/project/mozrunner/) package with a new ChromiumProfile but didn't upgrade the [mozprofile](https://pypi.org/project/mozprofile/) package.  Could be they did a partial push or something broke with the timing.  In the meantime I'm going to see if there is a way to force the previous mozrunner build instead

**Comment by pmeenan** [comment]
Should be "fixed" now. I hacked around it by forcing mozrunner to downgrade: https://github.com/WPO-Foundation/wptagent/commit/92c74deebbe5ef2958fb5b6bfd440e5f6c2e5f8a

Whenever they fix the issue I'll remove the forced downgrade (or eventually move to webdriver). In the meantime, your agents should start working over the next hour (or if you reboot them they will pick up the update immediately).

**Comment by zeman** [comment]
Woot, you're an absolute champ Pat! All working on our end.

**Comment by nilskuhn** [comment]
GREAT!
Thanks, Pat
