### ISSUE TITLE
Error processing V8 stats

### ISSUE THREAD

**Issue by GrigoreMihai** [WPO-Foundation/wptagent#314]
Hi, I am getting this error while trying to setup a test agent (also on the private instance I get "first view: test data missing" I think it comes from there). 

```
Error processing V8 stats
Traceback (most recent call last):
  File "/root/wptagent/internal/support/devtools_parser.py", line 1266, in process_v8_stats
    if os.path.isfile(self.v8_stats):
  File "/usr/lib64/python2.7/genericpath.py", line 29, in isfile
    st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```
The agent is running on centos 7. If you need more details you can ask me.

**Comment by thedoc31** [comment]
I submitted a PR to fix this, which was merged yesterday.

https://github.com/WPO-Foundation/wptagent/pull/323
