### ISSUE TITLE
Error processing log line

### ISSUE THREAD

**Issue by GrigoreMihai** [WPO-Foundation/wptagent#315]
Hi, I am getting this error while configuring an agent. 

Error processing log line
Traceback (most recent call last):
  File "/root/wptagent/internal/support/firefox_log_parser.py", line 154, in process_log_line
    day = int_map[timestamp[8:10]]
KeyError: 'ed'
Error processing log line
Traceback (most recent call last):
  File "/root/wptagent/internal/support/firefox_log_parser.py", line 154, in process_log_line
    day = int_map[timestamp[8:10]]
KeyError: 'or'
Error processing log line
Traceback (most recent call last):
  File "/root/wptagent/internal/support/firefox_log_parser.py", line 154, in process_log_line
    day = int_map[timestamp[8:10]]
KeyError: ': '
Error processing log line
Traceback (most recent call last):
  File "/root/wptagent/internal/support/firefox_log_parser.py", line 154, in process_log_line
    day = int_map[timestamp[8:10]]
KeyError: 'ty'
Error processing log line
Traceback (most recent call last):
  File "/root/wptagent/internal/support/firefox_log_parser.py", line 154, in process_log_line
    day = int_map[timestamp[8:10]]
KeyError: 'n,'
Error processing log line
Traceback (most recent call last):
  File "/root/wptagent/internal/support/firefox_log_parser.py", line 154, in process_log_line
    day = int_map[timestamp[8:10]]
KeyError: ' M'
Error processing log line
Traceback (most recent call last):
  File "/root/wptagent/internal/support/firefox_log_parser.py", line 154, in process_log_line
    day = int_map[timestamp[8:10]]
KeyError: 'nt'
Error processing log line
Traceback (most recent call last):
  File "/root/wptagent/internal/support/firefox_log_parser.py", line 154, in process_log_line
    day = int_map[timestamp[8:10]]
KeyError: 'op'
Error processing log line
Traceback (most recent call last):
  File "/root/wptagent/internal/support/firefox_log_parser.py", line 154, in process_log_line
    day = int_map[timestamp[8:10]]
KeyError: 'ie'
Error processing log line
Traceback (most recent call last):
  File "/root/wptagent/internal/support/firefox_log_parser.py", line 154, in process_log_line
    day = int_map[timestamp[8:10]]
KeyError: '"T'
Error processing log line
Traceback (most recent call last):
  File "/root/wptagent/internal/support/firefox_log_parser.py", line 154, in process_log_line
    day = int_map[timestamp[8:10]]
KeyError: ' q'
Error processing log line

It came after #312 was fixed. Running on centos 7.

**Comment by j0weiss** [comment]
I can confirm these error logs running the agent on Windows 10.
