### ISSUE TITLE
Enabling CPU throttling causes Docker container to fail

### ISSUE THREAD

**Issue by josebolos** [WPO-Foundation/wptagent#354]
I've been setting up a private instance using the docker image, and I've been struggling to enable CPU throttling for accurate mobile emulation. Passing the `--throttle` argument to wptagent would cause the Docker container to fail to run:

```sh
/usr/bin/docker run -d \
  -p 4001:80 \
  --init \
  --restart=unless-stopped \
  --shm-size=1g \
  --cap-add="NET_ADMIN" \
  --network="host" \
  -e "SERVER_URL=http://10.1.1.10/work/" \
  -e LOCATION="Location_1"
  -e "EXTRA_ARGS=--fps 60 --throttle -vvvv" \
  webpagetest/agent:20.05
```

I enabled the logging to maximum with `-vvvv` just in case. I was able to spot the following error in the log:

```
15:59:14.544 - Display: :1966105727
sudo: cgset: command not found
15:59:14.555 - sudo chmod -R 777 ~/.config/configstore/
```

So I did some investigation and it looks like the cgroup tools are not installed in the docker image, that's why `cgset` fails. I created another Docker image with the Dockerfile that follows that adds the missing package, and tried to enabled throttling again.

```
FROM webpagetest/agent:20.05

RUN apt-get update && \
  apt-get install -y cgroup-tools
```

This time the docker container started su cessfully but, when trying to run a test with CPU throttling, I obtained two different errors:

```
12:18:17.356 - CPU Throttle target: 3.236x
12:18:17.356 - sudo cgcreate -a root:root -t root:root -g cpu,cpuset:wptagent
cgcreate: can't create cgroup wptagent: Cgroup, operation not allowed
12:18:17.418 - Exception enabling throttling: Command '['sudo', 'cgcreate', '-a', 'root:root', '-t', 'root:root', '-g', 'cpu,cpuset:wptagent']' returned non-zero exit status 87
Traceback (most recent call last):
  File "/wptagent/internal/desktop_browser.py", line 756, in enable_cpu_throttling
    subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['sudo', 'cgcreate', '-a', 'root:root', '-t', 'root:root', '-g', 'cpu,cpuset:wptagent']' returned non-zero exit status 87
```

```
12:18:37.629 - sudo cgdelete -r cpu,cpuset:wptagent
cgdelete: cannot remove group 'wptagent': No such file or directory
12:18:37.685 - Error disabling throttling
Traceback (most recent call last):
  File "/wptagent/internal/desktop_browser.py", line 778, in disable_cpu_throttling
    subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['sudo', 'cgdelete', '-r', 'cpu,cpuset:wptagent']' returned non-zero exit status 96
```

After some googling, I found out that this is caused by the `/sys/fs/cgroup` filesystem being read-only. This can be fixed by adding `-v /sys/fs/cgroup:/sys/fs/cgroup:rw` to the runtime config to make it writeable, for example:

```sh
/usr/bin/docker run -d \
  -p 4001:80 \
  --init \
  --restart=unless-stopped \
  --shm-size=1g \
  --cap-add="NET_ADMIN" \
  --network="host" \
  -v /sys/fs/cgroup:/sys/fs/cgroup:rw \
  -e "SERVER_URL=http://10.1.1.10/work/" \
  -e LOCATION="Location_1"
  -e "EXTRA_ARGS=--fps 60 --throttle -vvvv" \
  webpagetest/agent:latest
```

This seems to have fixed the problem, and my private instance is now throttling the CPU.

I'm more than happy to create a PR in order to modify the Dockerfile and add a note somewhere in the documentation about the writable filesystem, but I've really never used Docker before, so I would appreciate if someone more familiar with Docker than I am could confirm if this makes sense and it's the right way to fix the issue without introducing any risks or security vulnerabilities.

**Comment by josebolos** [comment]
Closing as apparently cgroups-based throttling has been removed:
https://github.com/WPO-Foundation/wptagent/commit/f7fe0d6b5b01bd1b042a1fe3144c68a6bff846a6
