### ISSUE TITLE
Unable to initiate wpt agent

### ISSUE THREAD

**Issue by saikiran2612** [WPO-Foundation/wptagent#379]
I'm observing below error while trying to run below command in wpt agent. 
python wptagent.py -vvv --server http://10.1.153.25/work/ --location WPT_NewFra4
Python version installed: 2.7.13
Windows is: Windows server 2016

Error:
Traceback (most recent call last):
File "C:\wpt_agent_sep2018\wptagent\wptagent.py", line 705, in <module>
main()
File "C:\wpt_agent_sep2018\wptagent\wptagent.py", line 692, in main
browsers = find_browsers()
File "C:\wpt_agent_sep2018\wptagent\wptagent.py", line 465, in find_browsers
build = get_windows_build()
File "C:\wpt_agent_sep2018\wptagent\wptagent.py", line 395, in get_windows_build
return int(output.strip().split(' ')[-1])
ValueError: invalid literal for int() with base 10: ''

**Comment by pmeenan** [comment]
Should be fixed by [this commit](https://github.com/WPO-Foundation/wptagent/commit/ee7a5a57cf8e9cd65a9855a30023be2d61c5f46b) which will skip checks for legacy edge when it fails to get the windows build number.  If you pull the latest release branch it should work.

**Comment by saikiran2612** [comment]
Hi Meenan,

updated wptagent.py file with new release.

when i try with "python wptagent.py -vvv --server http://10.1.153.25/work/ --location WPT_Fra4"

observing the below error:
Traceback (most recent call last):
  File "wptagent.py", line 106, in run_testing
    self.job = self.wpt.get_test(self.browsers.browsers)
TypeError: get_test() takes exactly 1 argument (2 given)
23:47:55.028 - Unhandled exception: get_test() takes exactly 1 argument (2 given)
Traceback (most recent call last):
  File "wptagent.py", line 106, in run_testing
    self.job = self.wpt.get_test(self.browsers.browsers)
TypeError: get_test() takes exactly 1 argument (2 given)
