### ISSUE TITLE
wptagent does not start

### ISSUE THREAD

**Issue by amaralv** [WPO-Foundation/wptagent#422]
Trying to run wptagent in a private instance with the command:

```
/bin/python /opt/wptagent/wptagent.py --server 'http://server/work/' --location my_location --key myKey --xvfb --dockerized --shaper netem,eth0 --log /var/log/wptagent.log
```

I get this error:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/opt/wptagent/wptagent.py", line 270, in cleanup
    self.shaper.remove()
  File "/opt/wptagent/internal/traffic_shaping.py", line 68, in remove
    ret = self.shaper.remove()
  File "/opt/wptagent/internal/traffic_shaping.py", line 583, in remove
    if self.in_interface.startswith('ifb'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

Is this related with outdated dependencies?

**Comment by pmeenan** [comment]
Do you have the full log? That exception should only happen when it is already shutting down because of another error.  I just fixed that problem but my guess is a combination of dockerized and netem (you can't usually run netem inside of docker)

**Comment by pmeenan** [comment]
Run it with -vvvv to see everything that is going on

**Comment by amaralv** [comment]
Nothing related with the error:

```
RTNETLINK answers: Invalid argument
Traceback (most recent call last):
  File "/opt/wptagent/wptagent.py", line 1146, in <module>
    main()
  File "/opt/wptagent/wptagent.py", line 1137, in main
    if agent.startup(browsers):
  File "/opt/wptagent/wptagent.py", line 487, in startup
    self.shaper.remove()
  File "/opt/wptagent/internal/traffic_shaping.py", line 68, in remove
    ret = self.shaper.remove()
  File "/opt/wptagent/internal/traffic_shaping.py", line 583, in remove
    if self.in_interface.startswith('ifb'):
AttributeError: 'NoneType' object has no attribute 'startswith'
16:20:43.902 - Cleaning up
in_interface None
RTNETLINK answers: Invalid argument
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/opt/wptagent/wptagent.py", line 270, in cleanup
    self.shaper.remove()
  File "/opt/wptagent/internal/traffic_shaping.py", line 68, in remove
    ret = self.shaper.remove()
  File "/opt/wptagent/internal/traffic_shaping.py", line 583, in remove
    if self.in_interface.startswith('ifb'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/opt/wptagent/wptagent.py", line 270, in cleanup
    self.shaper.remove()
  File "/opt/wptagent/internal/traffic_shaping.py", line 68, in remove
    ret = self.shaper.remove()
  File "/opt/wptagent/internal/traffic_shaping.py", line 583, in remove
    if self.in_interface.startswith('ifb'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by pmeenan** [comment]
If you update from github that error should no longer happen.

**Comment by amaralv** [comment]
It works 👍🏿 
Can we have a patch to this? 

thanks

**Comment by pmeenan** [comment]
The commit was above near the top of the thread: https://github.com/WPO-Foundation/wptagent/commit/a2e3b839cb3678e68efe01f9ba49e4026cb8608d

**Comment by amaralv** [comment]
I was talking about a new release of wptagent with this fix. 
Does this make sense?

**Comment by pmeenan** [comment]
Done: https://github.com/WPO-Foundation/wptagent/releases/tag/21.07.1
