### ISSUE TITLE
xprop:  unable to open display ''

### ISSUE THREAD

**Issue by PetrHar** [WPO-Foundation/wptagent#458]
Hello,
i update server from debian 10 to 11.
I get an error after updating the server and agent:
` /usr/bin/python3 /home/agent/wptagent-master/wptagent.py --server "https://wpt.wpserver.cz/work/" --location "Test" -vvvv --dockerized --xvbf --sharper none --username wpt --password fHjbn84Q
22:02:23.460 - Detected Browsers:
22:02:23.460 - Chrome: /opt/google/chrome/chrome
22:02:23.460 - Chrome Beta: /opt/google/chrome-beta/chrome
22:02:23.460 - Chrome Dev: /opt/google/chrome-unstable/chrome
22:02:23.460 - Chrome Canary: /opt/google/chrome-unstable/chrome
22:02:23.460 - Canary: /opt/google/chrome-unstable/chrome
22:02:23.460 - Firefox: /usr/lib/firefox/firefox
22:02:23.460 - Firefox ESR: /usr/lib/firefox-esr/firefox-esr
22:02:23.594 - Interfaces:
22:02:23.594 - {'lo': [snicaddr(family=<AddressFamily.AF_INET: 2>, address='127.0.0.1', netmask='255.0.0.0', broadcast=None, ptp=None), snicaddr(family=<AddressFamily.AF_PACKET: 17>, address='00:00:00:00:00:00', netmask=None, broadcast=None, ptp=None)], 'venet0': [snicaddr(family=<AddressFamily.AF_INET: 2>, address='185.8.164.36', netmask='255.255.255.255', broadcast='185.8.164.36', ptp=None), snicaddr(family=<AddressFamily.AF_PACKET: 17>, address='d2:2a:ca:28:2f:77', netmask=None, broadcast='ff:ff:ff:ff:ff:ff', ptp=None)], 'tunl0': [snicaddr(family=<AddressFamily.AF_PACKET: 17>, address='00:00:00:00:00:00', netmask=None, broadcast=None, ptp=None)], 'gre0': [snicaddr(family=<AddressFamily.AF_PACKET: 17>, address='00:00:00:00:00:00', netmask=None, broadcast=None, ptp=None)], 'gretap0': [snicaddr(family=<AddressFamily.AF_PACKET: 17>, address='00:00:00:00:00:00', netmask=None, broadcast='ff:ff:ff:ff:ff:ff', ptp=None)], 'erspan0': [snicaddr(family=<AddressFamily.AF_PACKET: 17>, address='00:00:00:00:00:00', netmask=None, broadcast='ff:ff:ff:ff:ff:ff', ptp=None)]}
xprop:  unable to open display ''
Traceback (most recent call last):
  File "/home/agent/wptagent-master/wptagent.py", line 1185, in <module>
    main()
  File "/home/agent/wptagent-master/wptagent.py", line 1175, in main
    agent = WPTAgent(options, browsers)
  File "/home/agent/wptagent-master/wptagent.py", line 46, in __init__
    self.wpt = WebPageTest(options, os.path.join(self.root_path, "work"))
  File "/home/agent/wptagent-master/internal/webpagetest.py", line 157, in __init__
    out = subprocess.check_output(['xprop','-notype','-len','16','-root','_NET_DESKTOP_GEOMETRY'], universal_newlines=True)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['xprop', '-notype', '-len', '16', '-root', '_NET_DESKTOP_GEOMETRY']' returned non-zero exit status 1.`

**Comment by vlastimilott** [comment]
It seems like xprop is called although the script is running in headless mode. The reason for this might be getting current screen resolution which crashes within framebuffer. Is there any other way to get geometry? I'm not able to post a PR srry

**Comment by sharksforarms** [comment]
Also getting this when following GCE guide: https://docs.webpagetest.org/private-instances/gce_agents/#parameters

**Comment by sharksforarms** [comment]
@PetrHar see: https://github.com/WPO-Foundation/wptagent-install/issues/12
